[package]
name = "day19"
version = "0.1.0"
authors = ["Dan Walker <dwalker109@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
rand = "0.8"
rand_hc = "0.3"